### ISSUE TITLE
[Feature Request] Specific game message channel

### ISSUE THREAD

**Issue by buthed010203** [denverquane/automuteus#101]
Allow a config option to specify a channel to send game messages to that way we can have a channel just for messages and no other chat or spam.

**Comment by denverquane** [comment]
Yeah this is a good idea, appreciate the suggestion :)

**Comment by EricHedengren** [comment]
This would really only be useful if you want normal discord members to be able to run bot commands. And that's not very desirable anyways because they could troll by ending games, or other things. 

Currently you can simply create a restricted channel that you only send commands to, which is clean because the bot cleans up the commands you sent and it just has the current game message with no other chat, etc.

**Comment by buthed010203** [comment]
Its a server with a bunch of friends in it, its just nice to have all games in one central location. Honestly, I just suggested this cause I'm sure some people would end up using it. If I really needed this I would just have a bot delete all messages from non bot accounts in a channel lol

**Comment by denverquane** [comment]
This has been added and/or made defunct by newer updates. Multiple games can be ran in the same server, and they attach to individual text channels
