### ISSUE TITLE
Heroku bot keeps going offline after some time

### ISSUE THREAD

**Issue by NotIMaestro** [denverquane/automuteus#169]
Hello! first of all, thank you for making such an amazing bot and providing it to us free of charge!

im currently running it on a heroku app, and it works exactly as intended but after some time of not using the bot it decides to turn itself on and i have to manually turn it on again

i've googled it a bit and it seems like it's a problem of the dyno type.. mine is a web type but i don't get the option to change it into a worker type.. if anyone could help i would greatly appreciate it!

**Comment by mLgz0rn** [comment]
It's not a problem, it's doing as intended.
Because of you using a free plan, you get a limited amount of hours a month your app can be active (https://devcenter.heroku.com/articles/free-dyno-hours).
550 free hours, and you get 450 hours on top of that if you link your creditcard, you don't have to pay or anything.
So that's 1000 free hours every month.
Because of this your app will go sleeping after 30 min of inactivity I guess.

You can fix this by setting up some sort of pinging that pings your heroku app url every 30 min.
Can be done using New Relic's addon for heroku you can also use something like pingdom.
Just note that if you don't add your creditcard you will have 550 hours, which is not enough to keep the app running 24/7.
So you will need to make sure it sleeps around 6-7 hours every day, but not pinging the app at certain hours.

**Comment by NotIMaestro** [comment]
Alright, ill look into it! ty very much
