### ISSUE TITLE
docker errors with latest version

### ISSUE THREAD

**Issue by mLgz0rn** [denverquane/automuteus#290]
For some reason, I am unable to get the bot running on docker at the moment.

redis and postgres is running, but galactus is acting up.

this is just getting spammed in the galactus logs 

```
2020/11/24 21:05:37 No REDIS_USER specified.
2020/11/24 21:05:37 No REDIS_PASS specified.
2020/11/24 21:05:52 Locking token for 5 seconds
2020/11/24 21:06:02 Get "https://discord.com/api/v6/gateway": dial tcp: lookup discord.com on 127.0.0.11:53: read udp 127.0.0.1:44246->127.0.0.11:53: i/o timeout
2020/11/24 21:11:25 BOT HAS EXCEEDED TOKEN LOCKOUT ON PRIMARY TOKEN
2020/11/24 21:11:27 No REDIS_USER specified.
2020/11/24 21:11:27 No REDIS_PASS specified.
2020/11/24 21:11:27 BOT HAS EXCEEDED TOKEN LOCKOUT ON PRIMARY TOKEN
2020/11/24 21:11:30 No REDIS_USER specified.
2020/11/24 21:11:30 No REDIS_PASS specified.
```
and this in the automuteus logs

```
2020/11/24 21:07:50 -000dba7
2020/11/24 21:07:50 You provided 1 worker tokens so I'll be sending them to Galactus
2020/11/24 21:07:50 Error connecting to Galactus!
2020/11/24 21:07:50 Program exited with the following error:
2020/11/24 21:07:50 Get "http://galactus:5858/": dial tcp 172.21.0.2:5858: connect: connection refused
```
They are all running in the same docker network, so I don't get what the issue is.

Here is the redis and postgres logs

```
1:C 24 Nov 2020 21:05:51.591 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 24 Nov 2020 21:05:51.591 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 24 Nov 2020 21:05:51.592 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 24 Nov 2020 21:05:51.596 * Running mode=standalone, port=6379.
1:M 24 Nov 2020 21:05:51.596 # Server initialized
1:M 24 Nov 2020 21:05:51.597 * Loading RDB produced by version 6.0.9
1:M 24 Nov 2020 21:05:51.597 * RDB age 344 seconds
1:M 24 Nov 2020 21:05:51.597 * RDB memory usage when created 0.80 Mb
1:M 24 Nov 2020 21:05:51.597 * DB loaded from disk: 0.000 seconds
1:M 24 Nov 2020 21:05:51.597 * Ready to accept connections
```

```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2020-11-24 21:11:39.076 UTC [1] LOG:  starting PostgreSQL 12.5 (Debian 12.5-1.pgdg100+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2020-11-24 21:11:39.076 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-11-24 21:11:39.076 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2020-11-24 21:11:39.085 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-11-24 21:11:39.146 UTC [25] LOG:  database system was shut down at 2020-11-24 21:11:37 UTC
2020-11-24 21:11:39.161 UTC [1] LOG:  database system is ready to accept connections

```

Is this just me having an issue or?

kind regards

**Comment by denverquane** [comment]
So, Galactus has a lockout on any token provided to it, so that if it constantly restarts, it doesn't mistakenly exceed the maximum 1000 IDENTIFY / 24 hours that will cause Discord to email you and reset your token (I've been there -_-). Right now, Galactus has a softlimit of 40 Identifies in 1 hour (exceeding this will cause it to wait until it dips below 40/1hour before retrying that token again).

This data is all stored in redis, though. So if you completely remove the Redis volume, it would be an easy way to get around this limit while sorting out this issue.

However, I think the fundamental root of your problem is a networking issue with not being able to reach Discord.
This log:
`2020/11/24 21:06:02 Get "https://discord.com/api/v6/gateway": dial tcp: lookup discord.com on 127.0.0.11:53: read udp 127.0.0.1:44246->127.0.0.11:53: i/o timeout` seems to indicate a problem with your outgoing connection to Discord. Not sure if you have any special networking config, or need to purge namespace records, but something about the fundamental connection to Discord is failing, which is causing the other issues.

**Comment by mLgz0rn** [comment]
Hey @denverquane thanks for the response.

I got no clue whats going on, it seems like the containers don't have access to each other within the stack.
I think atleast I figures out the networking issue, my connection from my isp somehow went from a static ip which I pay for to a dynamic.
But that shouldn't cause any issues within docker itself, since it's locally the containers can't connect to each other.

**Comment by mLgz0rn** [comment]
Okay, so I got Galactus to connect to redis now, guess the bot token was blacklisted or something, so had to renew it.
However, I am still unable to connect from automuteus to galactus

`2020/12/05 21:18:20 -3b13e03
2020/12/05 21:18:20 Error connecting to Galactus!
2020/12/05 21:18:20 Program exited with the following error:
2020/12/05 21:18:20 Get "http://localhost:5858/": dial tcp 127.0.0.1:5858: connect: connection refused`

**Comment by mLgz0rn** [comment]
Alright I figured out the issue.

I had another docker container using port 8080, after changing the port on that it now works.
