### ISSUE TITLE
[Feature request] Name coloring by Discord role

### ISSUE THREAD

**Issue by TumoiYorozu** [denverquane/automuteus#307]
In voice chat, I want the name to be displayed in the same color as among us's character color.

I think this is feasible by creating a color role for it and adapting it to the character we select.

**Comment by ShawnHardwick** [comment]
Do you have an example where people's names in Discord voice chat are colored?

The bot previously had a similar functionality called `ApplyNicknames` that was removed due to the amount of maintenance and Discord API calls compared it's value. I imagine that this feature request is the same so may not be implemented.

I'll let @denverquane chime in.

**Comment by TumoiYorozu** [comment]
I was mistaken. Sorry
