### ISSUE TITLE
[BUG] Some players are slow to switch mutes when switching status

### ISSUE THREAD

**Issue by hibiki31** [denverquane/automuteus#450]
**Describe the bug**
When playing with more than 8 players, switching is often slow.

This happened both with official bots and with self-hosted bots.

**To Reproduce**
1. Play with 8 or more players.
2. Meeting's over.
3. Someone random is slow to mute.

**Expected behavior**
When switching status, everyone should switch immediately.

**Version of bot & capture**
 - Bot: [e.g. 6.15.2]
 - Capture: [e.g. 4.2.0]

**Additional Information**
When I was using the official bot, I thought the bot was crowded. However, the same phenomenon happened when I self-hosted it.

Please confirm.

**Comment by denverquane** [comment]
Unfortunately this is not a bug; this is due to Discord's rate limits. You can run the self-hosted bot with additional Bot Tokens to help distribute the load (and this is what Premium features of the official bot offer), but besides that, it's simply an issue of Discord only allowing a certain number of mute/deafen commands to be issued in a given time interval.

**Comment by hibiki31** [comment]
I didn't do enough research. Thank you very much.
